FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python3 -m pip install -U pip && \
    python3 -m pip install -U ultralytics pnnx ncnn

COPY yolo11_export_ncnn.py /app
